apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shipping 
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    environment: dev
    tier: backend
    code: shipping-roboshop-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      code: shipping-roboshop-dev
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        environment: dev
        tier: backend
        code: shipping-roboshop-dev
    spec:
      containers:
      - name: shipping-pod
        image: "{{ .Values.deployment.image_url }}:{{ .Values.deployment.image_version }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: shipping-configmap